# docker-compose.override.yml
# Solo para desarrollo local (no se sube a producción)

services:
  app_veterinaria:
    ports:
      - "8080:80"
    volumes:
      # Monta el código local para ver cambios en tiempo real
      - .:/var/www/html
    environment:
      DEV_MODE: "true"